# -*- coding: utf-8 -*-

"""
bitlyapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class References10(object):

    """Implementation of the 'References10' model.

    Attributes:
        quis_6 (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "quis_6": 'quis_6'
    }

    def __init__(self,
                 quis_6=None):
        """Constructor for the References10 class"""

        # Initialize members of the class
        self.quis_6 = quis_6 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        quis_6 = dictionary.get("quis_6") if dictionary.get("quis_6") else None
        # Return an object of this model
        return cls(quis_6)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'quis_6={self.quis_6!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'quis_6={self.quis_6!s})')
