
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-31T10:13:21-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "fdf4599646a5637c08ee8ba13674b64a0aa5ad42",
 "version": "2.67.1b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
