#!/usr/bin/env python
"""
Project package for metagit.

This package provides Pydantic models and methods for parsing and validating
.metagit.yml configuration files.
"""

from .manager import MetagitConfigManager
from .models import (
    CICD,
    AlertingChannel,
    AlertingChannelType,
    Artifact,
    ArtifactType,
    Branch,
    BranchNaming,
    BranchStrategy,
    CICDPlatform,
    ComponentKind,
    Dashboard,
    DependencyKind,
    Deployment,
    DeploymentStrategy,
    Environment,
    Hosting,
    Infrastructure,
    License,
    LicenseKind,
    LoggingProvider,
    Maintainer,
    MetagitConfig,
    MonitoringProvider,
    Observability,
    Pipeline,
    ProjectKind,
    ProjectPath,
    ProvisioningTool,
    Secret,
    SecretKind,
    Tasker,
    TaskerKind,
    Variable,
    VariableKind,
    VersionStrategy,
    Workspace,
    WorkspaceProject,
)

__all__ = [
    # Main configuration model
    "MetagitConfigManager",
    "MetagitConfig",
    # Enums
    "ProjectKind",
    "LicenseKind",
    "BranchStrategy",
    "TaskerKind",
    "ArtifactType",
    "VersionStrategy",
    "SecretKind",
    "VariableKind",
    "CICDPlatform",
    "DeploymentStrategy",
    "ProvisioningTool",
    "Hosting",
    "LoggingProvider",
    "MonitoringProvider",
    "AlertingChannelType",
    "ComponentKind",
    "DependencyKind",
    # Models
    "Maintainer",
    "License",
    "Tasker",
    "BranchNaming",
    "Branch",
    "Artifact",
    "Secret",
    "Variable",
    "Pipeline",
    "CICD",
    "Environment",
    "Infrastructure",
    "Deployment",
    "AlertingChannel",
    "Dashboard",
    "Observability",
    "ProjectPath",
    "Dependency",
    "Component",
    "WorkspaceProject",
    "Workspace",
]
