"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .compass_api_backend_models_pendle_read_response_markets_pendlemarket import (
    CompassAPIBackendModelsPendleReadResponseMarketsPendleMarket,
    CompassAPIBackendModelsPendleReadResponseMarketsPendleMarketTypedDict,
)
from compass_api_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CompassAPIBackendModelsPendleReadResponseMarketsPendleListMarketsResponseTypedDict(
    TypedDict
):
    markets: List[CompassAPIBackendModelsPendleReadResponseMarketsPendleMarketTypedDict]
    r"""A list of active markets on the inputted chain."""


class CompassAPIBackendModelsPendleReadResponseMarketsPendleListMarketsResponse(
    BaseModel
):
    markets: List[CompassAPIBackendModelsPendleReadResponseMarketsPendleMarket]
    r"""A list of active markets on the inputted chain."""
