from enum import IntEnum, StrEnum


class OrderType(IntEnum):
	ONLINE_STORE = 1
	REGULAR_DELIVERY = 2


class TariffCode(IntEnum):
	EXPRESS_DOOR_TO_DOOR = 1
	EXPRESS_DOOR_TO_PICKUP = 2
	EXPRESS_PICKUP_TO_DOOR = 3
	EXPRESS_PICKUP_TO_PICKUP = 4
	ECONOMY_DOOR_TO_DOOR = 5
	ECONOMY_DOOR_TO_PICKUP = 6
	ECONOMY_PICKUP_TO_DOOR = 7
	ECONOMY_PICKUP_TO_PICKUP = 8
	SUPER_EXPRESS_9_18 = 10
	SUPER_EXPRESS_10_16 = 11
	SUPER_EXPRESS_18_20 = 12
	OVERNIGHT_EXPRESS = 15
	ECONOMY_EXPRESS = 16
	CARGO_DOOR_TO_DOOR = 62
	CARGO_DOOR_TO_PICKUP = 63
	CARGO_PICKUP_TO_DOOR = 64
	CARGO_PICKUP_TO_PICKUP = 65
	EXPRESS_LIGHT = 136
	POSTAMAT = 137
	ECONOMY_PICKUP_TO_POSTAMAT = 138
	SUPER_EXPRESS_9_18_DOCUMENTS = 233
	ECONOMY_EXPRESS_PICKUP_TO_PICKUP = 234
	ECONOMY_EXPRESS_DOOR_TO_PICKUP = 235
	ECONOMY_EXPRESS_PICKUP_TO_DOOR = 236
	ECONOMY_EXPRESS_DOOR_TO_DOOR = 291
	ECONOMY_PICKUP_TO_PICKUP_STANDARD = 293
	ECONOMY_DOOR_TO_PICKUP_STANDARD = 294
	ECONOMY_PICKUP_TO_DOOR_STANDARD = 295
	ECONOMY_DOOR_TO_DOOR_STANDARD = 366
	ECONOMY_EXPRESS_WAREHOUSE = 368
	ECONOMY_EXPRESS_WAREHOUSE_PICKUP = 378
	POSTAMAT_DOOR = 480
	POSTAMAT_PICKUP = 481
	EXPRESS_LIGHT_PICKUP = 482
	EXPRESS_LIGHT_DOOR = 483
	CARGO_EXPRESS = 485
	CARGO_SUPER_EXPRESS = 486


class DeliveryMode(StrEnum):
	DOOR = "door"
	PICKUP = "pickup"
	POSTAMAT = "postamat"


class PackageType(StrEnum):
	PACKAGE = "package"
	ENVELOPE = "envelope"
	CARGO = "cargo"


class ServiceCode(StrEnum):
	INSURANCE = "INSURANCE"
	DANGEROUS_GOODS = "DANGEROUS_GOODS"
	TRYING_ON = "TRYING_ON"
	PARTIAL_DELIVERY = "PARTIAL_DELIVERY"
	INSPECTION_CARGO = "INSPECTION_CARGO"
	REVERSE_SHIPMENT = "REVERSE_SHIPMENT"
	DELIVERY_TO_FLOOR = "DELIVERY_TO_FLOOR"
	SMS_NOTIFICATION = "SMS_NOTIFICATION"
	CALL_NOTIFICATION = "CALL_NOTIFICATION"
	FRAGILE_CARGO = "FRAGILE_CARGO"
	OVERSIZED_CARGO = "OVERSIZED_CARGO"
	HEAVY_CARGO = "HEAVY_CARGO"
	TEMPERATURE_MODE = "TEMPERATURE_MODE"
	PAYMENT_CARD = "PAYMENT_CARD"
	CARGO_CHECK = "CARGO_CHECK"
	RETURN_RECEIPT = "RETURN_RECEIPT"
	DOCUMENTS_COPY = "DOCUMENTS_COPY"
	PHOTO_DOCUMENT = "PHOTO_DOCUMENT"
	PERSONAL_DELIVERY = "PERSONAL_DELIVERY"
	NOTIFICATIONS = "NOTIFICATIONS"
	COURIER_PACKAGE_A2 = "COURIER_PACKAGE_A2"
	COURIER_PACKAGE_A3 = "COURIER_PACKAGE_A3"
	COURIER_PACKAGE_A4 = "COURIER_PACKAGE_A4"
	COURIER_PACKAGE_A5 = "COURIER_PACKAGE_A5"
	SECURE_PACKAGE_A3 = "SECURE_PACKAGE_A3"
	SECURE_PACKAGE_A4 = "SECURE_PACKAGE_A4"
	SECURE_PACKAGE_A5 = "SECURE_PACKAGE_A5"


class OrderStatus(StrEnum):
	CREATED = "CREATED"
	ACCEPTED = "ACCEPTED"
	READY_FOR_SHIPMENT = "READY_FOR_SHIPMENT"
	SHIPPED = "SHIPPED"
	IN_TRANSIT = "IN_TRANSIT"
	IN_CITY = "IN_CITY"
	ARRIVED_AT_DELIVERY_POINT = "ARRIVED_AT_DELIVERY_POINT"
	DELIVERED = "DELIVERED"
	NOT_DELIVERED = "NOT_DELIVERED"
	RETURNED = "RETURNED"
	PARTIALLY_DELIVERED = "PARTIALLY_DELIVERED"
	CANCELLED = "CANCELLED"
	INVALID = "INVALID"


class PackageStatus(StrEnum):
	CREATED = "CREATED"
	ACCEPTED = "ACCEPTED"
	READY_FOR_SHIPMENT = "READY_FOR_SHIPMENT"
	SHIPPED = "SHIPPED"
	IN_TRANSIT = "IN_TRANSIT"
	IN_CITY = "IN_CITY"
	ARRIVED_AT_DELIVERY_POINT = "ARRIVED_AT_DELIVERY_POINT"
	DELIVERED = "DELIVERED"
	NOT_DELIVERED = "NOT_DELIVERED"
	RETURNED = "RETURNED"
	CANCELLED = "CANCELLED"


class DeliveryPointType(StrEnum):
	PVZ = "PVZ"
	POSTAMAT = "POSTAMAT"
	ALL = "ALL"


class PaymentMethod(StrEnum):
	CASH = "CASH"
	CARD = "CARD"


class WeightLimit(IntEnum):
	MIN_WEIGHT = 1
	MAX_WEIGHT_EXPRESS = 30000
	MAX_WEIGHT_ECONOMY = 50000
	MAX_WEIGHT_CARGO = 1500000


class DimensionLimit(IntEnum):
	MIN_DIMENSION = 1
	MAX_DIMENSION_EXPRESS = 150
	MAX_DIMENSION_ECONOMY = 200
	MAX_DIMENSION_CARGO = 300


class CountryCode(StrEnum):
	RUSSIA = "RU"
	KAZAKHSTAN = "KZ"
	BELARUS = "BY"
	ARMENIA = "AM"
	KYRGYZSTAN = "KG"
	CHINA = "CN"
	TURKEY = "TR"
	UZBEKISTAN = "UZ"
	SOUTH_KOREA = "KR"
	MONGOLIA = "MN"
	TAJIKISTAN = "TJ"
	THAILAND = "TH"
	INDIA = "IN"


class Currency(StrEnum):
	RUB = "RUB"
	USD = "USD"
	EUR = "EUR"
	KZT = "KZT"
	BYN = "BYN"
	AMD = "AMD"
	KGS = "KGS"
	CNY = "CNY"
	TRY = "TRY"
	UZS = "UZS"
	KRW = "KRW"
	MNT = "MNT"
	TJS = "TJS"
	THB = "THB"
	INR = "INR"


class VATRate(IntEnum):
	ZERO = 0
	TEN = 10
	TWENTY = 20


class PrintFormat(StrEnum):
	A4 = "A4"
	A5 = "A5"
	A6 = "A6"


class WebhookType(StrEnum):
	ORDER_STATUS = "ORDER_STATUS"
	PRINT_FORM = "PRINT_FORM"
	DELIVERY_STATUS = "DELIVERY_STATUS"


class Language(StrEnum):
	RU = "ru"
	EN = "en"
	ZH = "zh"
