# -*- coding: utf-8 -*-

"""
xero

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from xero.api_helper import APIHelper
from xero.configuration import Server
from xero.controllers.base_controller import BaseController
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter
from xero.http.http_method_enum import HttpMethodEnum
from apimatic_core.authentication.multiple.single_auth import Single
from xero.exceptions.a_failed_request_due_to_validation_error_exception import AFailedRequestDueToValidationErrorException


class PaymentsController(BaseController):

    """A Controller to access Endpoints in the xero API."""
    def __init__(self, config):
        super(PaymentsController, self).__init__(config)

    def allows_you_to_retrieve_payments_for_invoices_and_credit_notes(self,
                                                                      where,
                                                                      order,
                                                                      page,
                                                                      if_modified_since,
                                                                      xero_tenant_id):
        """Does a GET request to /Payments.

        Args:
            where (str): Filter by an any element
            order (str): Order by an any element
            page (str): Up to 100 payments will be returned in a single API
                call
            if_modified_since (str): Only records created or modified since
                this timestamp will be returned
            xero_tenant_id (str): (Required) Xero identifier for Tenant

        Returns:
            str: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/Payments')
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                         .key('where')
                         .value(where))
            .query_param(Parameter()
                         .key('order')
                         .value(order))
            .query_param(Parameter()
                         .key('page')
                         .value(page))
            .header_param(Parameter()
                          .key('If-Modified-Since')
                          .value(if_modified_since))
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
        ).execute()

    def allows_you_to_create_multiple_payments_for_invoices_or_credit_notes(self,
                                                                            summarize_errors,
                                                                            xero_tenant_id,
                                                                            body):
        """Does a PUT request to /Payments.

        Args:
            summarize_errors (bool): If false return 200 OK and mix of
                successfully created objects and any with validation errors
            xero_tenant_id (str): (Required) Xero identifier for Tenant
            body (AllowsYouToCreateMultiplePaymentsForInvoicesOrCreditNotesRequ
                est): The request body parameter.

        Returns:
            str: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/Payments')
            .http_method(HttpMethodEnum.PUT)
            .query_param(Parameter()
                         .key('summarizeErrors')
                         .value(summarize_errors))
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .local_error('400', 'Bad Request', AFailedRequestDueToValidationErrorException)
        ).execute()

    def allows_you_to_create_a_single_payment_for_invoices_or_credit_notes(self,
                                                                           xero_tenant_id,
                                                                           body):
        """Does a POST request to /Payments.

        Args:
            xero_tenant_id (str): (Required) Xero identifier for Tenant
            body (AllowsYouToCreateASinglePaymentForInvoicesOrCreditNotesReques
                t): The request body parameter.

        Returns:
            str: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/Payments')
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .local_error('400', 'Bad Request', AFailedRequestDueToValidationErrorException)
        ).execute()
