# coding: utf-8

"""
    e-KYC API

    e-KYC API , GST verification suite  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: gautam@balajimariline.com
    Generated by: https://openapi-generator.tech
"""

from vartulz_compliance_sdk.paths.v1_excel_getall_uploadid.get import GetAllUploadId
from vartulz_compliance_sdk.paths.v1_excel_get_uploadid_records.get import GetAllUploadIdRecords
from vartulz_compliance_sdk.paths.v1_excel_upload.post import UploadExcelFile


class ExcelManagementApi(
    GetAllUploadId,
    GetAllUploadIdRecords,
    UploadExcelFile,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
