from enum import Enum


class TokenFeatures(Enum):
    RNG = "CKF_RNG"
    CLOCK_ON_TOKEN = "CKF_CLOCK_ON_TOKEN"


class TokenOperability(Enum):
    WRITE_PROTECTED = "CKF_WRITE_PROTECTED"
    DUAL_CRYPTO_OPERATIONS = "CKF_DUAL_CRYPTO_OPERATIONS"
    RESTORE_KEY_NOT_NEEDED = "CKF_RESTORE_KEY_NOT_NEEDED"


class TokenInit(Enum):
    TOKEN_INITIALIZED = "CKF_TOKEN_INITIALIZED"
    USER_PIN_INITIALIZED = "CKF_USER_PIN_INITIALIZED"


class TokenAuthentication(Enum):
    LOGIN_REQUIRED = "CKF_LOGIN_REQUIRED"
    PROTECTED_AUTHENTICATION_PATH = "CKF_PROTECTED_AUTHENTICATION_PATH"
    SECONDARY_AUTHENTICATION = "CKF_SECONDARY_AUTHENTICATION"


class TokenUserPIN(Enum):
    USER_PIN_COUNT_LOW = "CKF_USER_PIN_COUNT_LOW"
    USER_PIN_FINAL_TRY = "CKF_USER_PIN_FINAL_TRY"
    USER_PIN_LOCKED = "CKF_USER_PIN_LOCKED"
    USER_PIN_TO_BE_CHANGED = "CKF_USER_PIN_TO_BE_CHANGED"


class TokenSOPIN(Enum):
    SO_PIN_COUNT_LOW = "CKF_SO_PIN_COUNT_LOW"
    SO_PIN_FINAL_TRY = "CKF_SO_PIN_FINAL_TRY"
    SO_PIN_LOCKED = "CKF_SO_PIN_LOCKED"
    SO_PIN_TO_BE_CHANGED = "CKF_SO_PIN_TO_BE_CHANGED"
