__all__ = [
    "current_npu_device",
    "is_compile_log_enabled",
    "log_dir",
    "xdg_state_home",
]

def current_npu_device() -> str: ...
def is_compile_log_enabled() -> bool: ...
def log_dir() -> str: ...
def xdg_state_home() -> str: ...
