# coding: utf-8

"""
    e-KYC API

    e-KYC API , GST verification suite  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: gautam@balajimariline.com
    Generated by: https://openapi-generator.tech
"""

from vartulz_compliance_sdk.paths.v1_nsdl_get_signatory_details_case_id.get import GetSignatoryDetails
from vartulz_compliance_sdk.paths.v1_nsdl_update_signatory_details_case_id.post import UpdateSignatoryDetails


class MCASignatoryDetailsManagementApi(
    GetSignatoryDetails,
    UpdateSignatoryDetails,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
