# -*- coding: utf-8 -*-

"""
coingeckopublicapiv3

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from coingeckopublicapiv3.api_helper import APIHelper


class BannerImage(object):

    """Implementation of the 'BannerImage' model.

    NFT collection banner image url

    Attributes:
        small (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "small": 'small'
    }

    _optionals = [
        'small',
    ]

    def __init__(self,
                 small=APIHelper.SKIP):
        """Constructor for the BannerImage class"""

        # Initialize members of the class
        if small is not APIHelper.SKIP:
            self.small = small 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        small = dictionary.get("small") if dictionary.get("small") else APIHelper.SKIP
        # Return an object of this model
        return cls(small)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'small={(self.small if hasattr(self, "small") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'small={(self.small if hasattr(self, "small") else None)!s})')
