# -*- coding: utf-8 -*-

"""
trello

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from trello.api_helper import APIHelper


class CardsChecklistIdChecklistCurrentCheckItem(object):

    """Implementation of the 'cards_checklist_idChecklistCurrent_checkItem' model.

    Attributes:
        id_checklist (str): An id, or null
        name (str): a string with a length from 1 to 16384
        pos (str): A position. top , bottom , or a positive number.
        state (str): One of: complete, false, incomplete or true

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id_checklist": 'idChecklist',
        "name": 'name',
        "pos": 'pos',
        "state": 'state'
    }

    _optionals = [
        'id_checklist',
        'name',
        'pos',
        'state',
    ]

    def __init__(self,
                 id_checklist=APIHelper.SKIP,
                 name=APIHelper.SKIP,
                 pos=APIHelper.SKIP,
                 state=APIHelper.SKIP):
        """Constructor for the CardsChecklistIdChecklistCurrentCheckItem class"""

        # Initialize members of the class
        if id_checklist is not APIHelper.SKIP:
            self.id_checklist = id_checklist 
        if name is not APIHelper.SKIP:
            self.name = name 
        if pos is not APIHelper.SKIP:
            self.pos = pos 
        if state is not APIHelper.SKIP:
            self.state = state 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id_checklist = dictionary.get("idChecklist") if dictionary.get("idChecklist") else APIHelper.SKIP
        name = dictionary.get("name") if dictionary.get("name") else APIHelper.SKIP
        pos = dictionary.get("pos") if dictionary.get("pos") else APIHelper.SKIP
        state = dictionary.get("state") if dictionary.get("state") else APIHelper.SKIP
        # Return an object of this model
        return cls(id_checklist,
                   name,
                   pos,
                   state)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'id_checklist={(self.id_checklist if hasattr(self, "id_checklist") else None)!r}, '
                f'name={(self.name if hasattr(self, "name") else None)!r}, '
                f'pos={(self.pos if hasattr(self, "pos") else None)!r}, '
                f'state={(self.state if hasattr(self, "state") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'id_checklist={(self.id_checklist if hasattr(self, "id_checklist") else None)!s}, '
                f'name={(self.name if hasattr(self, "name") else None)!s}, '
                f'pos={(self.pos if hasattr(self, "pos") else None)!s}, '
                f'state={(self.state if hasattr(self, "state") else None)!s})')
