# coding: utf-8

"""
    e-KYC API

    e-KYC API , GST verification suite  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: gautam@balajimariline.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import vartulz_compliance_sdk
from vartulz_compliance_sdk.model.login_request_body import LoginRequestBody
from vartulz_compliance_sdk import configuration


class TestLoginRequestBody(unittest.TestCase):
    """LoginRequestBody unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
