# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tests.testdata.ping.v1 import ping_pb2 as tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tests/testdata/ping/v1/ping_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PingServiceStub(object):
    """*
    PingService defines example RPCs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/tests.testdata.ping.v1.PingService/Ping',
                request_serializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingRequest.SerializeToString,
                response_deserializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingResponse.FromString,
                _registered_method=True)
        self.PingServerStream = channel.unary_stream(
                '/tests.testdata.ping.v1.PingService/PingServerStream',
                request_serializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingRequest.SerializeToString,
                response_deserializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingResponse.FromString,
                _registered_method=True)
        self.PingClientStream = channel.stream_unary(
                '/tests.testdata.ping.v1.PingService/PingClientStream',
                request_serializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingRequest.SerializeToString,
                response_deserializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingResponse.FromString,
                _registered_method=True)
        self.PingBidiStream = channel.stream_stream(
                '/tests.testdata.ping.v1.PingService/PingBidiStream',
                request_serializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingRequest.SerializeToString,
                response_deserializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingResponse.FromString,
                _registered_method=True)


class PingServiceServicer(object):
    """*
    PingService defines example RPCs.
    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PingServerStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PingClientStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PingBidiStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingRequest.FromString,
                    response_serializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingResponse.SerializeToString,
            ),
            'PingServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PingServerStream,
                    request_deserializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingRequest.FromString,
                    response_serializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingResponse.SerializeToString,
            ),
            'PingClientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.PingClientStream,
                    request_deserializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingRequest.FromString,
                    response_serializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingResponse.SerializeToString,
            ),
            'PingBidiStream': grpc.stream_stream_rpc_method_handler(
                    servicer.PingBidiStream,
                    request_deserializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingRequest.FromString,
                    response_serializer=tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tests.testdata.ping.v1.PingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tests.testdata.ping.v1.PingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PingService(object):
    """*
    PingService defines example RPCs.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tests.testdata.ping.v1.PingService/Ping',
            tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingRequest.SerializeToString,
            tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PingServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tests.testdata.ping.v1.PingService/PingServerStream',
            tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingRequest.SerializeToString,
            tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PingClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/tests.testdata.ping.v1.PingService/PingClientStream',
            tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingRequest.SerializeToString,
            tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PingBidiStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tests.testdata.ping.v1.PingService/PingBidiStream',
            tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingRequest.SerializeToString,
            tests_dot_testdata_dot_ping_dot_v1_dot_ping__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
