# -*- coding: utf-8 -*-

"""
lobapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class To4(object):

    """Implementation of the 'To4' model.

    Attributes:
        id (str): The model property of type str.
        description (str): The model property of type str.
        name (str): The model property of type str.
        company (str): The model property of type str.
        phone (str): The model property of type str.
        email (str): The model property of type str.
        address_line_1 (str): The model property of type str.
        address_line_2 (str): The model property of type str.
        address_city (str): The model property of type str.
        address_state (str): The model property of type str.
        address_zip (str): The model property of type str.
        address_country (str): The model property of type str.
        metadata (Any): The model property of type Any.
        date_created (str): The model property of type str.
        date_modified (str): The model property of type str.
        object (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "description": 'description',
        "name": 'name',
        "company": 'company',
        "phone": 'phone',
        "email": 'email',
        "address_line_1": 'address_line1',
        "address_line_2": 'address_line2',
        "address_city": 'address_city',
        "address_state": 'address_state',
        "address_zip": 'address_zip',
        "address_country": 'address_country',
        "metadata": 'metadata',
        "date_created": 'date_created',
        "date_modified": 'date_modified',
        "object": 'object'
    }

    _nullables = [
        'description',
        'company',
        'phone',
        'email',
        'address_line_2',
    ]

    def __init__(self,
                 id=None,
                 description=None,
                 name=None,
                 company=None,
                 phone=None,
                 email=None,
                 address_line_1=None,
                 address_line_2=None,
                 address_city=None,
                 address_state=None,
                 address_zip=None,
                 address_country=None,
                 metadata=None,
                 date_created=None,
                 date_modified=None,
                 object=None):
        """Constructor for the To4 class"""

        # Initialize members of the class
        self.id = id 
        self.description = description 
        self.name = name 
        self.company = company 
        self.phone = phone 
        self.email = email 
        self.address_line_1 = address_line_1 
        self.address_line_2 = address_line_2 
        self.address_city = address_city 
        self.address_state = address_state 
        self.address_zip = address_zip 
        self.address_country = address_country 
        self.metadata = metadata 
        self.date_created = date_created 
        self.date_modified = date_modified 
        self.object = object 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get("id") if dictionary.get("id") else None
        description = dictionary.get("description") if dictionary.get("description") else None
        name = dictionary.get("name") if dictionary.get("name") else None
        company = dictionary.get("company") if dictionary.get("company") else None
        phone = dictionary.get("phone") if dictionary.get("phone") else None
        email = dictionary.get("email") if dictionary.get("email") else None
        address_line_1 = dictionary.get("address_line1") if dictionary.get("address_line1") else None
        address_line_2 = dictionary.get("address_line2") if dictionary.get("address_line2") else None
        address_city = dictionary.get("address_city") if dictionary.get("address_city") else None
        address_state = dictionary.get("address_state") if dictionary.get("address_state") else None
        address_zip = dictionary.get("address_zip") if dictionary.get("address_zip") else None
        address_country = dictionary.get("address_country") if dictionary.get("address_country") else None
        metadata = dictionary.get("metadata") if dictionary.get("metadata") else None
        date_created = dictionary.get("date_created") if dictionary.get("date_created") else None
        date_modified = dictionary.get("date_modified") if dictionary.get("date_modified") else None
        object = dictionary.get("object") if dictionary.get("object") else None
        # Return an object of this model
        return cls(id,
                   description,
                   name,
                   company,
                   phone,
                   email,
                   address_line_1,
                   address_line_2,
                   address_city,
                   address_state,
                   address_zip,
                   address_country,
                   metadata,
                   date_created,
                   date_modified,
                   object)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'id={self.id!r}, '
                f'description={self.description!r}, '
                f'name={self.name!r}, '
                f'company={self.company!r}, '
                f'phone={self.phone!r}, '
                f'email={self.email!r}, '
                f'address_line_1={self.address_line_1!r}, '
                f'address_line_2={self.address_line_2!r}, '
                f'address_city={self.address_city!r}, '
                f'address_state={self.address_state!r}, '
                f'address_zip={self.address_zip!r}, '
                f'address_country={self.address_country!r}, '
                f'metadata={self.metadata!r}, '
                f'date_created={self.date_created!r}, '
                f'date_modified={self.date_modified!r}, '
                f'object={self.object!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'id={self.id!s}, '
                f'description={self.description!s}, '
                f'name={self.name!s}, '
                f'company={self.company!s}, '
                f'phone={self.phone!s}, '
                f'email={self.email!s}, '
                f'address_line_1={self.address_line_1!s}, '
                f'address_line_2={self.address_line_2!s}, '
                f'address_city={self.address_city!s}, '
                f'address_state={self.address_state!s}, '
                f'address_zip={self.address_zip!s}, '
                f'address_country={self.address_country!s}, '
                f'metadata={self.metadata!s}, '
                f'date_created={self.date_created!s}, '
                f'date_modified={self.date_modified!s}, '
                f'object={self.object!s})')
