# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import vartulz_compliance_sdk
from vartulz_compliance_sdk.paths.v1_nsdl_update_iec_details_case_id import post  # noqa: E501
from vartulz_compliance_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1NsdlUpdateIecDetailsCaseId(ApiTestMixin, unittest.TestCase):
    """
    V1NsdlUpdateIecDetailsCaseId unit test stubs
        Update IEC details from NSDL  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
