# coding: utf-8

"""
    RESTful.Service

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.roster_activity_flight_details import RosterActivityFlightDetails  # noqa: E501
from swagger_client.rest import ApiException


class TestRosterActivityFlightDetails(unittest.TestCase):
    """RosterActivityFlightDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRosterActivityFlightDetails(self):
        """Test RosterActivityFlightDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.roster_activity_flight_details.RosterActivityFlightDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
