# coding: utf-8

"""
    RESTful.Service

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.configuration_data_api import ConfigurationDataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigurationDataApi(unittest.TestCase):
    """ConfigurationDataApi unit test stubs"""

    def setUp(self):
        self.api = ConfigurationDataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_configuration_data_get_aircraft_types(self):
        """Test case for configuration_data_get_aircraft_types

        Get aircraft types optionally filtered by name, IATA code, or ICAO code.  # noqa: E501
        """
        pass

    def test_configuration_data_get_bases(self):
        """Test case for configuration_data_get_bases

        Get bases optionally filtered by name, short code, or base type.  # noqa: E501
        """
        pass

    def test_configuration_data_get_crew_complements(self):
        """Test case for configuration_data_get_crew_complements

        Get crew complements optionally filtered by name or short code.  # noqa: E501
        """
        pass

    def test_configuration_data_get_hotel_information(self):
        """Test case for configuration_data_get_hotel_information

        Get hotel information optionally filtered by name or code.  # noqa: E501
        """
        pass

    def test_configuration_data_get_hr_documents(self):
        """Test case for configuration_data_get_hr_documents

        Get HR documents optionally filtered by their name, code, or document type.  # noqa: E501
        """
        pass

    def test_configuration_data_get_hr_types(self):
        """Test case for configuration_data_get_hr_types

        Get HR types optionally filtered by their name, short code, type, or main type.  # noqa: E501
        """
        pass

    def test_configuration_data_get_leg_legal_exceptions(self):
        """Test case for configuration_data_get_leg_legal_exceptions

        Get legal exceptions for legs optionally filtered by name or short code.  # noqa: E501
        """
        pass

    def test_configuration_data_get_note_types(self):
        """Test case for configuration_data_get_note_types

        Get NoteType optionally filtered by their name or Datatype.  # noqa: E501
        """
        pass

    def test_configuration_data_get_projects(self):
        """Test case for configuration_data_get_projects

        Get projects optionally filtered by name, short code, project number, cost center, or company.  # noqa: E501
        """
        pass

    def test_configuration_data_get_ranks(self):
        """Test case for configuration_data_get_ranks

        Get Ranks optionally filtered by their name,shortcode or type.  # noqa: E501
        """
        pass

    def test_configuration_data_get_reason_categories(self):
        """Test case for configuration_data_get_reason_categories

        Get reason categories optionally filtered by their code.  # noqa: E501
        """
        pass

    def test_configuration_data_get_reasons(self):
        """Test case for configuration_data_get_reasons

        Get reasons optionally filtered by code.  # noqa: E501
        """
        pass

    def test_configuration_data_get_reference_activities(self):
        """Test case for configuration_data_get_reference_activities

        Get reference activities optionally filtered by name or short code.  # noqa: E501
        """
        pass

    def test_configuration_data_get_roster_designators(self):
        """Test case for configuration_data_get_roster_designators

        Get roster designators optionally filtered by name or short code.  # noqa: E501
        """
        pass

    def test_configuration_data_get_roster_legal_exceptions(self):
        """Test case for configuration_data_get_roster_legal_exceptions

        Get roster legal exceptions optionally filtered by their name or short code.  # noqa: E501
        """
        pass

    def test_configuration_data_get_sepcial_roles(self):
        """Test case for configuration_data_get_sepcial_roles

        Get special roles optionally filtered by role type, roster pattern, and equipment qualification.  # noqa: E501
        """
        pass

    def test_configuration_data_get_transaction_codes(self):
        """Test case for configuration_data_get_transaction_codes

        Get transaction codes optionally filtered by their name or short code.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
