# coding: utf-8

"""
    RESTful.Service

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.aircraft_in import AircraftIn  # noqa: E501
from swagger_client.rest import ApiException


class TestAircraftIn(unittest.TestCase):
    """AircraftIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAircraftIn(self):
        """Test AircraftIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.aircraft_in.AircraftIn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
