# generated by fastapi-codegen:
#   filename:  /home/ivasylen/sdk_project/contracts/guardicore/connector
#   timestamp: 2025-07-31T14:14:32+00:00

from __future__ import annotations

from enum import Enum


class Connector(Enum):
    CLOUD_AZURE = 'cloud_azure'
    CLOUD_AWS = 'cloud_aws'
    PACKETFENCE = 'packetfence'
    ALGOSEC = 'algosec'
    PENSANDO = 'pensando'
