
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-07-30T23:09:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ae2feef81fb1b47f2168bd728eacbb90a744e498",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
