# coding: utf-8

"""
    e-KYC API

    e-KYC API , GST verification suite  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: gautam@balajimariline.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from vartulz_compliance_sdk import schemas  # noqa: F401


class MCASignatoryRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "clientData",
            "consent",
        }
        
        class properties:
            consent = schemas.StrSchema
        
            @staticmethod
            def clientData() -> typing.Type['CaseDetails']:
                return CaseDetails
            cin = schemas.StrSchema
            iec = schemas.StrSchema
            companyName = schemas.StrSchema
            __annotations__ = {
                "consent": consent,
                "clientData": clientData,
                "cin": cin,
                "iec": iec,
                "companyName": companyName,
            }
    
    clientData: 'CaseDetails'
    consent: MetaOapg.properties.consent
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["consent"]) -> MetaOapg.properties.consent: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clientData"]) -> 'CaseDetails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["cin"]) -> MetaOapg.properties.cin: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["iec"]) -> MetaOapg.properties.iec: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["companyName"]) -> MetaOapg.properties.companyName: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["consent", "clientData", "cin", "iec", "companyName", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["consent"]) -> MetaOapg.properties.consent: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clientData"]) -> 'CaseDetails': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["cin"]) -> typing.Union[MetaOapg.properties.cin, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["iec"]) -> typing.Union[MetaOapg.properties.iec, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["companyName"]) -> typing.Union[MetaOapg.properties.companyName, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["consent", "clientData", "cin", "iec", "companyName", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        clientData: 'CaseDetails',
        consent: typing.Union[MetaOapg.properties.consent, str, ],
        cin: typing.Union[MetaOapg.properties.cin, str, schemas.Unset] = schemas.unset,
        iec: typing.Union[MetaOapg.properties.iec, str, schemas.Unset] = schemas.unset,
        companyName: typing.Union[MetaOapg.properties.companyName, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MCASignatoryRequest':
        return super().__new__(
            cls,
            *_args,
            clientData=clientData,
            consent=consent,
            cin=cin,
            iec=iec,
            companyName=companyName,
            _configuration=_configuration,
            **kwargs,
        )

from vartulz_compliance_sdk.model.case_details import CaseDetails
