# -*- coding: utf-8 -*-

"""
aviationstack

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Flight4(object):

    """Implementation of the 'Flight4' model.

    Attributes:
        number (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "number": 'number'
    }

    def __init__(self,
                 number=None):
        """Constructor for the Flight4 class"""

        # Initialize members of the class
        self.number = number 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        number = dictionary.get("number") if dictionary.get("number") else None
        # Return an object of this model
        return cls(number)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'number={self.number!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'number={self.number!s})')
