# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions

from .report_anthropic_request_req_payload_zero_tools_item_cache_control_cache_control_type import (
    ReportAnthropicRequestReqPayloadZeroToolsItemCacheControlCacheControlType,
)

ReportAnthropicRequestReqPayloadZeroToolsItemCacheControlCacheControl = typing.Union[
    ReportAnthropicRequestReqPayloadZeroToolsItemCacheControlCacheControlType,
    typing.Optional[typing_extensions.Literal["null"]],
]
