# This file was auto-generated by Fern from our API Definition.

import typing

from .report_anthropic_request_req_payload_one_tools_item_cache_control import (
    ReportAnthropicRequestReqPayloadOneToolsItemCacheControl,
)
from .report_anthropic_request_req_payload_one_tools_item_description import (
    ReportAnthropicRequestReqPayloadOneToolsItemDescription,
)
from .report_anthropic_request_req_payload_one_tools_item_one import ReportAnthropicRequestReqPayloadOneToolsItemOne

ReportAnthropicRequestReqPayloadOneToolsItem = typing.Union[
    ReportAnthropicRequestReqPayloadOneToolsItemDescription,
    ReportAnthropicRequestReqPayloadOneToolsItemOne,
    ReportAnthropicRequestReqPayloadOneToolsItemCacheControl,
]
