IDENTIFIER = "<identifier>"
INT_LITERAL = "<int-literal>"
FLOAT_LITERAL = "<float-literal>"
STRING_LITERAL = "<string-literal>"
FILENAME_LITERAL = "<filename-literal>"
COMMENT = "<comment>"
EOL = "\n"
