# -*- coding: utf-8 -*-

"""
xero

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from xero.models.tax_rate import TaxRate


class AllowsYouToUpdateTaxRatesRequest(object):

    """Implementation of the 'Allows you to update Tax Rates Request' model.

    Attributes:
        tax_rates (List[TaxRate]): The model property of type List[TaxRate].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tax_rates": 'TaxRates'
    }

    def __init__(self,
                 tax_rates=None):
        """Constructor for the AllowsYouToUpdateTaxRatesRequest class"""

        # Initialize members of the class
        self.tax_rates = tax_rates 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        tax_rates = None
        if dictionary.get('TaxRates') is not None:
            tax_rates = [TaxRate.from_dictionary(x) for x in dictionary.get('TaxRates')]
        # Return an object of this model
        return cls(tax_rates)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'tax_rates={self.tax_rates!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'tax_rates={self.tax_rates!s})')
