# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
from .chat_completion_tool_message_param_content import ChatCompletionToolMessageParamContent
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ChatCompletionToolMessageParam(UncheckedBaseModel):
    content: ChatCompletionToolMessageParamContent
    role: typing.Literal["tool"] = "tool"
    tool_call_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
