# This file was auto-generated by Fern from our API Definition.

import typing
from .local_sandbox_config import LocalSandboxConfig
from .e_2_b_sandbox_config import E2BSandboxConfig

SandboxConfigUpdateConfig = typing.Union[LocalSandboxConfig, E2BSandboxConfig]
