# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions

CreateModelRequestTrainingConfigOpenpipeHyperparametersBatchSize = typing.Union[
    typing_extensions.Literal["auto"], float
]
