# -*- coding: utf-8 -*-

"""
aviationstack

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Datum6(object):

    """Implementation of the 'Datum6' model.

    Attributes:
        id (str): The model property of type str.
        gmt (str): The model property of type str.
        airport_id (str): The model property of type str.
        iata_code (str): The model property of type str.
        city_iata_code (str): The model property of type str.
        icao_code (str): The model property of type str.
        country_iso_2 (str): The model property of type str.
        geoname_id (str): The model property of type str.
        latitude (str): The model property of type str.
        longitude (str): The model property of type str.
        airport_name (str): The model property of type str.
        country_name (str): The model property of type str.
        phone_number (str): The model property of type str.
        timezone (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "gmt": 'gmt',
        "airport_id": 'airport_id',
        "iata_code": 'iata_code',
        "city_iata_code": 'city_iata_code',
        "icao_code": 'icao_code',
        "country_iso_2": 'country_iso2',
        "geoname_id": 'geoname_id',
        "latitude": 'latitude',
        "longitude": 'longitude',
        "airport_name": 'airport_name',
        "country_name": 'country_name',
        "phone_number": 'phone_number',
        "timezone": 'timezone'
    }

    _nullables = [
        'gmt',
        'country_name',
        'phone_number',
    ]

    def __init__(self,
                 id=None,
                 gmt=None,
                 airport_id=None,
                 iata_code=None,
                 city_iata_code=None,
                 icao_code=None,
                 country_iso_2=None,
                 geoname_id=None,
                 latitude=None,
                 longitude=None,
                 airport_name=None,
                 country_name=None,
                 phone_number=None,
                 timezone=None):
        """Constructor for the Datum6 class"""

        # Initialize members of the class
        self.id = id 
        self.gmt = gmt 
        self.airport_id = airport_id 
        self.iata_code = iata_code 
        self.city_iata_code = city_iata_code 
        self.icao_code = icao_code 
        self.country_iso_2 = country_iso_2 
        self.geoname_id = geoname_id 
        self.latitude = latitude 
        self.longitude = longitude 
        self.airport_name = airport_name 
        self.country_name = country_name 
        self.phone_number = phone_number 
        self.timezone = timezone 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get("id") if dictionary.get("id") else None
        gmt = dictionary.get("gmt") if dictionary.get("gmt") else None
        airport_id = dictionary.get("airport_id") if dictionary.get("airport_id") else None
        iata_code = dictionary.get("iata_code") if dictionary.get("iata_code") else None
        city_iata_code = dictionary.get("city_iata_code") if dictionary.get("city_iata_code") else None
        icao_code = dictionary.get("icao_code") if dictionary.get("icao_code") else None
        country_iso_2 = dictionary.get("country_iso2") if dictionary.get("country_iso2") else None
        geoname_id = dictionary.get("geoname_id") if dictionary.get("geoname_id") else None
        latitude = dictionary.get("latitude") if dictionary.get("latitude") else None
        longitude = dictionary.get("longitude") if dictionary.get("longitude") else None
        airport_name = dictionary.get("airport_name") if dictionary.get("airport_name") else None
        country_name = dictionary.get("country_name") if dictionary.get("country_name") else None
        phone_number = dictionary.get("phone_number") if dictionary.get("phone_number") else None
        timezone = dictionary.get("timezone") if dictionary.get("timezone") else None
        # Return an object of this model
        return cls(id,
                   gmt,
                   airport_id,
                   iata_code,
                   city_iata_code,
                   icao_code,
                   country_iso_2,
                   geoname_id,
                   latitude,
                   longitude,
                   airport_name,
                   country_name,
                   phone_number,
                   timezone)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'id={self.id!r}, '
                f'gmt={self.gmt!r}, '
                f'airport_id={self.airport_id!r}, '
                f'iata_code={self.iata_code!r}, '
                f'city_iata_code={self.city_iata_code!r}, '
                f'icao_code={self.icao_code!r}, '
                f'country_iso_2={self.country_iso_2!r}, '
                f'geoname_id={self.geoname_id!r}, '
                f'latitude={self.latitude!r}, '
                f'longitude={self.longitude!r}, '
                f'airport_name={self.airport_name!r}, '
                f'country_name={self.country_name!r}, '
                f'phone_number={self.phone_number!r}, '
                f'timezone={self.timezone!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'id={self.id!s}, '
                f'gmt={self.gmt!s}, '
                f'airport_id={self.airport_id!s}, '
                f'iata_code={self.iata_code!s}, '
                f'city_iata_code={self.city_iata_code!s}, '
                f'icao_code={self.icao_code!s}, '
                f'country_iso_2={self.country_iso_2!s}, '
                f'geoname_id={self.geoname_id!s}, '
                f'latitude={self.latitude!s}, '
                f'longitude={self.longitude!s}, '
                f'airport_name={self.airport_name!s}, '
                f'country_name={self.country_name!s}, '
                f'phone_number={self.phone_number!s}, '
                f'timezone={self.timezone!s})')
