# -*- coding: utf-8 -*-

"""
xero

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from xero.api_helper import APIHelper
from xero.configuration import Server
from xero.controllers.base_controller import BaseController
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter
from xero.http.http_method_enum import HttpMethodEnum
from apimatic_core.authentication.multiple.single_auth import Single
from xero.exceptions.a_failed_request_due_to_validation_error_exception import AFailedRequestDueToValidationErrorException


class InvoiceIDController(BaseController):

    """A Controller to access Endpoints in the xero API."""
    def __init__(self, config):
        super(InvoiceIDController, self).__init__(config)

    def allows_you_to_retrieve_a_specified_sales_invoice_or_purchase_bill(self,
                                                                          unitdp,
                                                                          invoice_id,
                                                                          xero_tenant_id):
        """Does a GET request to /Invoices/{InvoiceID}.

        Args:
            unitdp (str): e.g. unitdp=4 – (Unit Decimal Places) You can opt in
                to use four decimal places for unit amounts
            invoice_id (str): (Required) Unique identifier for an Invoice
            xero_tenant_id (str): (Required) Xero identifier for Tenant

        Returns:
            str: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/Invoices/{InvoiceID}')
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                         .key('unitdp')
                         .value(unitdp))
            .template_param(Parameter()
                            .key('InvoiceID')
                            .value(invoice_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
        ).execute()

    def allows_you_to_update_a_specified_sales_invoices_or_purchase_bills(self,
                                                                          unitdp,
                                                                          invoice_id,
                                                                          xero_tenant_id,
                                                                          body):
        """Does a POST request to /Invoices/{InvoiceID}.

        Args:
            unitdp (str): e.g. unitdp=4 – (Unit Decimal Places) You can opt in
                to use four decimal places for unit amounts
            invoice_id (str): (Required) Unique identifier for an Invoice
            xero_tenant_id (str): (Required) Xero identifier for Tenant
            body (AllowsYouToUpdateASpecifiedSalesInvoicesOrPurchaseBillsReques
                t): The request body parameter.

        Returns:
            str: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/Invoices/{InvoiceID}')
            .http_method(HttpMethodEnum.POST)
            .query_param(Parameter()
                         .key('unitdp')
                         .value(unitdp))
            .template_param(Parameter()
                            .key('InvoiceID')
                            .value(invoice_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .local_error('400', 'Bad Request', AFailedRequestDueToValidationErrorException)
        ).execute()

    def allows_you_to_retrieve_invoices_or_purchase_bills_as_pdf_files(self,
                                                                       invoice_id,
                                                                       xero_tenant_id):
        """Does a GET request to /Invoices/{InvoiceID}/pdf.

        Args:
            invoice_id (str): (Required) Unique identifier for an Invoice
            xero_tenant_id (str): (Required) Xero identifier for Tenant

        Returns:
            str: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/Invoices/{InvoiceID}/pdf')
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                            .key('InvoiceID')
                            .value(invoice_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
        ).execute()

    def allows_you_to_retrieve_a_url_to_an_online_invoice(self,
                                                          invoice_id,
                                                          xero_tenant_id):
        """Does a GET request to /Invoices/{InvoiceID}/OnlineInvoice.

        Args:
            invoice_id (str): (Required) Unique identifier for an Invoice
            xero_tenant_id (str): (Required) Xero identifier for Tenant

        Returns:
            str: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/Invoices/{InvoiceID}/OnlineInvoice')
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                            .key('InvoiceID')
                            .value(invoice_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
        ).execute()

    def allows_you_to_email_a_copy_of_invoice_to_related_contact(self,
                                                                 invoice_id,
                                                                 xero_tenant_id,
                                                                 body):
        """Does a POST request to /Invoices/{InvoiceID}/Email.

        Args:
            invoice_id (str): (Required) Unique identifier for an Invoice
            xero_tenant_id (str): (Required) Xero identifier for Tenant
            body (AllowsYouToEmailACopyOfInvoiceToRelatedContactRequest): The
                request body parameter.

        Returns:
            Any: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/Invoices/{InvoiceID}/Email')
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                            .key('InvoiceID')
                            .value(invoice_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.dynamic_deserialize)
            .local_error('400', 'Bad Request', AFailedRequestDueToValidationErrorException)
        ).execute()
