# -*- coding: utf-8 -*-

"""
geodbcitiesapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PopulatedPlaceTypeEnum(object):

    """Implementation of the 'PopulatedPlaceType' enum.

    One of a set of enumerated populated-place types known by the service
    (currently only level-2 admin divisions and
    cities)

    Attributes:
        ADM2: The enum member of type str.
        CITY: The enum member of type str.

    """
    ADM2 = 'ADM2'

    CITY = 'CITY'

