# Generated by Django 3.1.13 on 2021-09-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_allow_blank_value_on_station_fields_of_observations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='waterfall',
            new_name='waterfall_old',
        ),
    ]
