# Generated by Django 4.0.4 on 2022-06-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_add_basic_client_configuration_in_station_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='client_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
