DEFAULT_SYMBOL: str = '_'
DEFAULT_DISTANCE: int = 10
DEFAULT_CONTEXT_SIZE: int = 10
DEFAULT_KEEP_COUNT: int = 2
MAX_TEXT_LENGTH: int = 200000
REMOVE_GAP_MIN_LENGTH: int = 10
ROOT_TAG: str = 'body'
KEEP_SPACE_ONLY: bool = False