# coding: utf-8

"""
    e-KYC API

    e-KYC API , GST verification suite  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: gautam@balajimariline.com
    Generated by: https://openapi-generator.tech
"""

from vartulz_compliance_sdk.paths.v1_barcode_generatre_barcode.get import CreateNewBarCode
from vartulz_compliance_sdk.paths.v1_barcode_get_aadhar_details.get import GetAadharDetails
from vartulz_compliance_sdk.paths.v1_barcode_get_bank_details.get import GetAllBankFromBarcode
from vartulz_compliance_sdk.paths.v1_barcode_get_master_details.get import GetCompanyMasterDetailsFromBarcode
from vartulz_compliance_sdk.paths.v1_barcode_get_pan_details.get import GetDetailsFromPanNumberBarcode
from vartulz_compliance_sdk.paths.v1_barcode_get_gstin_details.get import GetDetailsGstinBarcode
from vartulz_compliance_sdk.paths.v1_barcode_get_electricity_details.get import GetElectricityDetails1
from vartulz_compliance_sdk.paths.v1_barcode_get_gstin_status_gstin.get import GetGstinStatusBarcode
from vartulz_compliance_sdk.paths.v1_barcode_get_iec_details.get import GetIecDetailsFromBarcode
from vartulz_compliance_sdk.paths.v1_barcode_get_gstin_preference_details_gstin.get import GetPreferenceDetailsGstinBarcode
from vartulz_compliance_sdk.paths.v1_barcode_get_signatory_details.get import GetSignatoryDetailsFromBarcode
from vartulz_compliance_sdk.paths.v1_barcode_get_gstin_track_details_gstin.get import GetTrackDetailsGstinBarcode
from vartulz_compliance_sdk.paths.v1_barcode_share_barcode.post import SharebarCode


class BarcodeManagementApi(
    CreateNewBarCode,
    GetAadharDetails,
    GetAllBankFromBarcode,
    GetCompanyMasterDetailsFromBarcode,
    GetDetailsFromPanNumberBarcode,
    GetDetailsGstinBarcode,
    GetElectricityDetails1,
    GetGstinStatusBarcode,
    GetIecDetailsFromBarcode,
    GetPreferenceDetailsGstinBarcode,
    GetSignatoryDetailsFromBarcode,
    GetTrackDetailsGstinBarcode,
    SharebarCode,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
