# coding: utf-8

"""
    e-KYC API

    e-KYC API , GST verification suite  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: gautam@balajimariline.com
    Generated by: https://openapi-generator.tech
"""

from vartulz_compliance_sdk.paths.v1_biller_get_all_biller.get import GetAllBiller
from vartulz_compliance_sdk.paths.v1_biller_get_all_bystate_state.get import GetAllBillerByState
from vartulz_compliance_sdk.paths.v1_biller_get_all_state.get import GetAllState


class ElectricityBillerManagementApi(
    GetAllBiller,
    GetAllBillerByState,
    GetAllState,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
