

from typing import List


DEFAULT_BOT_DETECTION_METHODS: List = []

DEFAULT_BOT_DETECTION_MAX_RETRIES: int = 3

DEFAULT_BOT_DETECTION_RETRY_WAIT_TIME: int = 20 # Seconds

DEFAULT_BOT_DETECTION_WAIT_FOR_PRESENCE_DELAY: int = 1 # Seconds